### PR TITLE
Fix multiple connections problems to one same nqn in a single node

### LINKED ISSUE #22: Failure to mount volumes with a same nqn more than twice in a single node
I tried to test the csi driver for nvme over tcp in a kubernetes cluster. But I encountered some problems when I mount volumes with a same nqn more than twice in a single node.

First problem is that it's not possible reconnect with a same nqn more than twice in a single mode. And second problem is that it's not possible readonly and readwrite mounts simultaneously for one block device.

Thank you very much.

### PR DESCRIPTION
**Pull request by haruband**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This makes multiple connections to one same nqn possible in a single node and makes readonly and readwrite mounts simultaneously for one block device.

**Which issue(s) this PR fixes**:
Fixes #22

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
None

```release-note
none
```

### CODE REVIEW

**Review by andyzhangx — COMMENTED** [review]
/ok-to-test

File: pkg/nvmf/fabrics.go [hunk 1]
```diff
@@ -115,24 +168,55 @@ func disconnectSubsys(nqn, ctrl string) (res bool) {
...
 		}
 	}
+
+	nqnPath := strings.Join([]string{RUN_NVMF, nqn}, "/")
+	hostnqns, err := ioutil.ReadDir(nqnPath)
+	if err != nil {
+		klog.Errorf("Disconnect: readdir %s err: %v", nqnPath, err)
+		return -ENOENT
+	}
+	if len(hostnqns) <= 0 {
```
Comment (MeinhardZhou) [inline pkg/nvmf/fabrics.go:200]: \>= ?

File: pkg/nvmf/fabrics.go [hunk 2]
```diff
@@ -154,33 +238,57 @@ func (c *Connector) Connect() (string, error) {
...
-		ret := disconnectByNqn(c.TargetNqn)
+		ret := disconnectByNqn(c.TargetNqn, c.HostNqn)
+		if ret < 0 {
+			klog.Errorf("rollback error !!!")
+		}
+		return "", err
+	}
+
+	// create nqn directory
+	nqnPath := strings.Join([]string{RUN_NVMF, c.TargetNqn}, "/")
```
Comment (MeinhardZhou) [inline pkg/nvmf/fabrics.go:261]: Ditto

File: pkg/nvmf/fabrics.go [hunk 3]
```diff
@@ -154,33 +238,57 @@ func (c *Connector) Connect() (string, error) {
...
+		klog.Errorf("create nqn directory %s error %v, rollback!!!", c.TargetNqn, err)
+		ret := disconnectByNqn(c.TargetNqn, c.HostNqn)
 		if ret < 0 {
 			klog.Errorf("rollback error !!!")
 		}
 		return "", err
 	}
 
+	// create hostnqn file
+	hostnqnPath := strings.Join([]string{RUN_NVMF, c.TargetNqn, b64.StdEncoding.EncodeToString([]byte(c.HostNqn))}, "/")
```
Comment (MeinhardZhou) [inline pkg/nvmf/fabrics.go:272]: Ditto

File: pkg/nvmf/const.go [hunk 4]
```diff
@@ -18,6 +18,7 @@ package nvmf
 const (
 	NVMF_NQN_SIZE = 223
 	SYS_NVMF      = "/sys/class/nvme"
+	RUN_NVMF      = "/run/nvmf"
```
[the remark this answers is not in the document]
Comment (haruband) [reply pkg/nvmf/const.go:21]: I used "/run/..." which is a tmpfs because subsysnqns and hostnqns should be deleted after rebooting accidentally. So, do you think it's better to make a directory and mount it as tmpfs in "/var/lib/kubelet/plugins/csi.nvmf.com/..."?

[the remark this answers is not in the document]
Comment (MeinhardZhou) [reply pkg/nvmf/const.go:21]: Got it. I mistakenly thought it was possible to restore on the same node. You are right.

File: pkg/nvmf/fabrics.go [hunk 5]
```diff
@@ -115,24 +168,55 @@ func disconnectSubsys(nqn, ctrl string) (res bool) {
...
-func disconnectByNqn(nqn string) int {
+func disconnectByNqn(nqn, hostnqn string) int {
 	ret := 0
 	if len(nqn) > NVMF_NQN_SIZE {
 		klog.Errorf("Disconnect: nqn %s is too long ", nqn)
 		return -EINVAL
 	}
 
+	// delete hostnqn file
+	hostnqnPath := strings.Join([]string{RUN_NVMF, nqn, b64.StdEncoding.EncodeToString([]byte(hostnqn))}, "/")
```
[the remark this answers is not in the document]
Comment (haruband) [reply pkg/nvmf/fabrics.go:179]: Okay, I will use path.Join() instead of strings.join(), but still we need base64 encoding. Because a hostnqn which is NodeUnpublishVolumeRequest's targetPath contains "/" characters.

File: pkg/nvmf/fabrics.go [hunk 6]
```diff
@@ -115,24 +168,55 @@ func disconnectSubsys(nqn, ctrl string) (res bool) {
...
 	}
 
 	for _, device := range devices {
-		if disconnectSubsys(nqn, device.Name()) {
+		if disconnectSubsysWithHostNqn(nqn, hostnqn, device.Name()) {
 			ret++
 		}
 	}
+
+	nqnPath := strings.Join([]string{RUN_NVMF, nqn}, "/")
```
[the remark this answers is not in the document]
Comment (haruband) [reply pkg/nvmf/fabrics.go:194]: It's a directory for subsysnqn per each nqn.

File: pkg/nvmf/fabrics.go (hunk 1 above)
Comment (haruband) [reply pkg/nvmf/fabrics.go:200]: If there is no more files for hostnqn, we will delete a directory for subsysnqn. It's fallback scenario when linux kernel has no sysfs hostnqn file supports. So, it's not wrong.

File: pkg/nvmf/fabrics.go [hunk 7]
```diff
@@ -84,6 +87,56 @@ func _disconnect(sysfs_path string) error {
 	return nil
 }
 
+func disconnectSubsysWithHostNqn(nqn, hostnqn, ctrl string) (res bool) {
+	sysfs_nqn_path := fmt.Sprintf("%s/%s/subsysnqn", SYS_NVMF, ctrl)
```
[the remark this answers is not in the document]
Comment (haruband) [reply pkg/nvmf/fabrics.go:91]: It's better for me to use subsysnqn and hostnqn, how about this?

File: pkg/nvmf/fabrics.go (hunk 1 above)
Comment (MeinhardZhou) [reply pkg/nvmf/fabrics.go:200]: If the Linux kernel does not have sysfs hostnqn file support, `disconnectSubsysWithHostNqn` will always return false, and `ret` will be always 0, but the hostnqn file we created will always exist, so `len(hostnqns)` will be greater than 0, and the fallback scenario will not work.

By the way, could we move `disconnectSubsysWithHostNqn` and `disconnectSubsys` into a loop, then when `disconnectSubsysWithHostNqn` failed,  we can execute `disconnectSubsys` to disconnect all connections instead of looping twice?

Comment (haruband) [reply pkg/nvmf/fabrics.go]: The hostnqn file we created will not always exist, because we delete the hostnqn file at the beginning of disconnectByNqn().

And I removed the looping twice problem through returning explicitly UnsupportedHostnqnError.

**Comment by MeinhardZhou** [comment]
@haruband 
I have tested and passed without any problems :)

But there is a small problem, can we map the host's `/run/nvmf` to `csi-node-driver`, so that we can not explicitly create this directory? (of course, we can also check it)

**Comment by haruband** [comment]
@MeinhardZhou 
Okay, got it. I will check it!
